version: '3.8'

services:
  node_app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: captcha_app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/users
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: captcha_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: